ymaps/codestyle

javascript.md

The previous version of this rule is ambiguous.

[EN] Fixed an ambigious rule for multiline statements

---

packages/eslint-config-loris/es5.js
packages/eslint-config-loris/es6.js
packages/eslint-config-loris/package.json

Migration guide: http://eslint.org/docs/user-guide/migrating-to-2.0.0
Changes:
1. Enable `strict` rule in `es5.js` config too.
2. Change `strict` rule value to [safe](http://eslint.org/docs/rules/strict#safe-default).

eslint-config: support eslint 2.x

---

packages/jscs-preset-loris/preset.json

This operands are default ones for this rule:
https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/disallow-space-before-postfix-unary-operators.js#L29
https://github.com/jscs-dev/node-jscs/blob/master/lib/utils.js#L186

"disallowSpaceBeforePostfixUnaryOperators": true

---

packages/jscs-preset-loris/preset.json

Comma is no longer considered a binary operator [since 2.0.0](http://jscs.info/changelog#version-2-0-0-https-github-comjscs-devnode-jscscomparev1-13-1-v2-0-0):
> Utils: remove comma from list of binary operators (Oleg Gaidarenko)

Rewrite old rule for spaces around comma

---

packages/eslint-config-loris/es5.js

**Current behavior:**
* `eslint` allows 2 consecutive blank lines
* `eslint` allows 2 consecutive blank lines at the end of file
**New behavior:**
* `eslint` allows **only** 1 blank line
* `eslint` doesn't allow blank line at the end of file
For more information about options of rule see http://eslint.org/docs/rules/no-multiple-empty-lines#options

eslint-config: Improve "no-multiple-empty-lines" rule

---

javascript.md

Instead of deleting `loop` section I added style guides for loop statements. 
Related with https://github.com/ymaps/codestyle/pull/28

Replace preferences to style for loop statements

---

packages/eslint-config-loris/es5.js

Ref: eslint/eslint#6341
tl;dr Non-ASCII characters are not allowed in identifiers for variables.

eslint-config: Add 'id-match' rule

---

javascript.md

* Additional eslint configuration isn't needed, because [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops) already covers this case.
* There is another point of view from PEP8 http://stackoverflow.com/questions/8853063/pep-8-why-no-spaces-around-in-keyword-argument-or-a-default-parameter-value

es6: default parameters

---

javascript.md
packages/eslint-config-loris/es6.js

* Describe style for computed property names. This style is checked using [computed-property-spacing](http://eslint.org/docs/rules/computed-property-spacing)
eslint rule.
* Add [no-useless-computed-key](http://eslint.org/docs/rules/no-useless-computed-key)
eslint rule to `es6` config.

Add style for computed property names

---

javascript.md

I often see this pattern
```js
function Foo(bar) {
if (!(this instanceof Foo)) {
return new Foo(bar);
}
// ...
}
```
It allows to create new instance without new:
```js
var foo = Foo(); // same as var foo = new Foo();
```
In my opinion it makes code unclear: if you need factory function - just make factory function, don't use constructor for this. Moreover, in `ES6` `TypeError` will be thrown if try to call constructor without `new`.
So, I suggest to prohibit this pattern.

Disallow usage constructors as factory functions

---

packages/eslint-config-loris/es5.js
packages/eslint-config-loris/es6.js

* [unicode-bom](http://eslint.org/docs/rules/unicode-bom)
* [no-tabs](http://eslint.org/docs/rules/no-tabs)
* [no-useless-constructor](http://eslint.org/docs/rules/no-useless-constructor)
* [no-useless-rename](http://eslint.org/docs/rules/no-useless-rename)
* [no-new-symbol](http://eslint.org/docs/rules/no-new-symbol)
* [no-empty-pattern](http://eslint.org/docs/rules/no-empty-pattern) is moved from `es5` to `es6`.

Update eslint rules (fixes #67)

---

javascript.md
packages/eslint-config-loris/es6.js

Add `allowNamedFunctions` option to `prefer-callback` rule.
Documentation: http://eslint.org/docs/rules/prefer-arrow-callback#allownamedfunctions
Named function expression is useful for debugging, because in stack
trace function has name.

eslint-config: allow named functions in prefer-callback rule

---

packages/eslint-config-loris/es5.js

Add new rules to eslint `loris/es5` config:
* [semi-style](https://eslint.org/docs/4.0.0/rules/semi-style)
* [switch-colon-spacing](https://eslint.org/docs/rules/switch-colon-spacing)
Both rules are available since `eslint v4.0.0`.

eslint: add semi-style, switch-colon-spacing rules

---

packages/tslint-config-loris/index.js
typescript.md

Bad:
```ts
type A = string|number;
type A = string| number;
type A = string |number;
```
Good:
```ts
type A = string | number;
```

tslint-config: add 'check-type-operator' to 'whitespace' rule

---

.npmrc
javascript.md
packages/eslint-config-loris/README.md
packages/eslint-config-loris/es2017.js
packages/tslint-config-loris/index.js

* Add [no-return-await](https://eslint.org/docs/rules/no-return-await) to `eslint` config.
* Add [no-return-await](https://palantir.github.io/tslint/rules/no-return-await/) to `tslint` config.
* Describe this rule in `javascript.md` file.
* Add new `es2017` preset to `eslint-config-loris`.

Add no-return-await rule

---

javascript.md

This rule based on Dart's rule
https://www.dartlang.org/guides/language/effective-dart/usage#dont-use-async-when-it-has-no-useful-effect
Fixes #108

DON'T use async when it has no useful effect

---

.gitignore
packages/tslint-config-loris/README.md
packages/tslint-config-loris/package.json

There are no objectives to include `tslint-eslint-rules` as peer
dependency, because it can be updated after reinstall `tslint-config-loris`
package.

Include tslint-eslint-rules as normal dependency

---

javascript.md

This rule describes current behavior of `tslint` and `eslint` configurations. 
Fixes #97

Describe import spacing rule

---

packages/tslint-config-loris/index.js

Forbid `public` modifier usage in `tslint` according to  current style guide rule: https://github.com/ymaps/codestyle/blob/master/typescript.md#classes
Documentation links:
* [`member-access`](https://palantir.github.io/tslint/rules/member-access/) rule (available in `tslint >= 5.0.0` https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v500)

tslint-config: Forbid public modifier for members

---

packages/tslint-config-loris/index.js
typescript.md

Most of our projects use `as` syntax for type assertions.

tslint-config: Disallow angle bracker type assertions
