ymaps/codestyle

javascript.md, javascript.ru.md
=> Add name convention for function arguments

javascript.md, javascript.ru.md
Relevant to https://github.com/yandex/codestyle/issues/33
=> es6: classes

javascript.md, javascript.ru.md
=> add style for enum (close #34)

javascript.md, javascript.ru.md
Relevant to https://github.com/yandex/codestyle/issues/33
=> es6: const, let

README.md
Relevant to https://github.com/ymaps/codestyle/issues/33
=> es6: generators

README.md
https://github.com/ymaps/codestyle/issues/33
=> es6: strict mode

README.md
https://github.com/ymaps/codestyle/issues/33
=> es6: arrow functions

javascript.md
Main issue https://github.com/ymaps/codestyle/issues/33
First pull request https://github.com/ymaps/codestyle/pull/48
**Changes**
1. Always use parentheses around parameters.
2. ~~Describe some edge cases (e.g. export declaration).~~
=> es6: arrow function (attempt 2)

README.md, packages/eslint-config-loris/README.md, packages/eslint-config-loris/es5.js, packages/eslint-config-loris/es6.js, packages/eslint-config-loris/package.json
link with https://github.com/ymaps/codestyle/issues/10
=> add package with eslint config

packages/jscs-preset-loris/README.md, packages/jscs-preset-loris/package.json
=> jscs-preset: add jscs as peer dependency

javascript.md
Main issue https://github.com/ymaps/codestyle/issues/33
=> es6: template strings

javascript.md
This pull request describes style for [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment). All this rules already checked with current `eslint` configuration.
=> es6: destructuring assignment

packages/eslint-config-loris/es5.js
Rule details: http://eslint.org/docs/rules/padded-blocks
=> eslint-config: disallow padding within blocks

packages/eslint-config-loris/es5.js
Rule details: http://eslint.org/docs/rules/no-unsafe-finally
=> eslint-config: enable no-unsafe-finally

javascript.md
=> Remove preferences for event names

README.md, package.json, typescript.md
This is the beginning of work on TS style guide. The purpose of this is to consolidate our practices into one formal document and follow it in all our TS code (like we do with JS).
Let's work out what to add, what not to add.
=> TS style guide: inception

typescript.md
Documentation: http://www.typescriptlang.org/docs/handbook/enums.html
=> ts: Use const enum whenever possible

typescript.md
=> ts: Describe type assertion style

packages/eslint-config-loris/README.md, packages/eslint-config-loris/package.json, packages/eslint-config-loris/react.js
=> eslint-config: add react configuration

typescript.md
=> ts: Add rule for leading _ in private and protected fields

typescript.md
=> ts: uppercase for enum values

README.md, packages/tslint-config-loris/README.md, packages/tslint-config-loris/index.js, packages/tslint-config-loris/package.json
https://github.com/ymaps/codestyle/issues/92
=> tslint-config-loris
